### ISSUE TITLE
当 history 文件为旧版生成或不存在时程序崩溃

### ISSUE THREAD

**Issue by YouXam** [byrdocs/byrdocs-cli#7]
程序没有兼容旧版本的 history 文件，当升级到新版本后进入交互式生成文件信息后会直接崩溃。手动删除 history 文件后依然崩溃。

```
❯ byrdocs
    __                   __
   / /_  __  ___________/ /___  __________
  / __ \/ / / / ___/ __  / __ \/ ___/ ___/
 / /_/ / /_/ / /  / /_/ / /_/ / /__(__  )
/_.___/\__, /_/   \__,_/\____/\___/____/
      /____/

? 请选择操作 交互式生成文件元信息文件
Traceback (most recent call last):
  File "/Users/youxam/.local/bin/byrdocs", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/__init__.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/__init__.py", line 146, in main
    _ask_for_init(None, False)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/__init__.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/__init__.py", line 112, in _ask_for_init
    ask_for_init(file_name, manually)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/yaml_init.py", line 208, in ask_for_init
    if not manually and ((recent_file_choices_resp := get_recent_file_choices()) is not None):
                                                      ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/yaml_init.py", line 80, in get_recent_file_choices
    history = history.get()
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/history_manager.py", line 47, in wrapper
    self._read()
    ~~~~~~~~~~^^
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/history_manager.py", line 37, in _read
    self.data = json.load(f)
                ~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 293, in load
    return loads(fp.read(),
        cls=cls, object_hook=object_hook,
        parse_float=parse_float, parse_int=parse_int,
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by NoNormalCreeper** [comment]
明日修复

**Comment by NoNormalCreeper** [comment]
已初步修复，现在当文件格式不正确/文件不存在时均会创建新的历史文件。

https://github.com/byrdocs/byrdocs-cli/commit/bb258493d58815240c78c736c8baaa8a1a4f0660

待你测试后发布版本。

**Comment by YouXam** [comment]
测试通过
