### ISSUE TITLE
进入选择功能界面后无法上传文件

### ISSUE THREAD

**Issue by YouXam** [byrdocs/byrdocs-cli#8]
```
❯ byrdocs
    __                   __
   / /_  __  ___________/ /___  __________
  / __ \/ / / / ___/ __  / __ \/ ___/ ___/
 / /_/ / /_/ / /  / /_/ / /_/ / /__(__  )
/_.___/\__, /_/   \__,_/\____/\___/____/
      /____/

? 请选择操作 上传文件
? 选择上传的文件路径 /Users/youxam/code/byrdocs/byrdocs-stockpile/bupt-cs-gallery-main/网络存储技术/皮人杰PPT/归档.zip
Traceback (most recent call last):
  File "/Users/youxam/.local/bin/byrdocs", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/__init__.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/__init__.py", line 215, in main
    if (file_type := get_file_type(file)) == "unsupported":
                     ~~~~~~~~~~~~~^^^^^^
  File "/Users/youxam/.local/pipx/venvs/byrdocs-cli/lib/python3.13/site-packages/byrdocs/__init__.py", line 82, in get_file_type
    elif magic_number == b"PK\x03\x04" and file.endswith(".zip"):
                                           ^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

可以正常使用命令行参数传递文件路径

**Comment by NoNormalCreeper** [comment]
我未能成功复现该问题，可以提供下版本号和环境吗？

**Comment by NoNormalCreeper** [comment]
> 我未能成功复现该问题，可以提供下版本号和环境吗？

现在复现了，不用了（）

**Comment by NoNormalCreeper** [comment]
已初步修复：[b8f8e0](https://github.com/byrdocs/byrdocs-cli/commit/b8f8e06ba98ac5bb8152d2812208d98e553d336d)

稍候与另一个 Bug 一起发版。

**Comment by YouXam** [comment]
测试通过
